spring.application.name=second-wind

spring.datasource.url=jdbc:postgresql://localhost:5433/second_wind
spring.datasource.username=postgres
spring.datasource.password=1939
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect